apiVersion: v1
kind: Service
metadata:
  namespace: freelance
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: backend
