apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freelance
  labels:
    io.kompose.service: certbot-webroot
  name: certbot-webroot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
