apiVersion: v1
kind: Service
metadata:
  namespace: freelance
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3000
  selector:
    io.kompose.service: grafana
